server:
  port: 9300
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    gateway:
      routes:
        # 系统管理服务
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - PreserveHostHeader=true
        # 危险源服务
        - id: task
          uri: lb://task
          predicates:
            - Path=/task/**
          filters:
            - PreserveHostHeader=true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        default-filters:
          - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        # 主库
        master:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://localhost:3306/labwe_system?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: root
          password: root
  redis:
    host: localhost
    port: 6379
    password: cSmart@redis2020
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1 #最大阻塞等待时间（-1表示没有限制）
        min-idle: 0 #最小空闲连接
        max-idle: 8 #最大空闲连接
        timeout: 3000 #连接超时时间ms

management:
  endpoints:
    web:
      exposure:
        include: '*'